services:
  fastapi_crawler_redis:
    image: redis:6-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  fastapi_crawler_db:
    image: postgres:14-alpine
    volumes:
      - ./fastapi_crawler_db/:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi_user -d fastapi_crawler"]
      interval: 30s
      timeout: 10s
      retries: 3

  fastapi-crawler_app:
    build: .
    ports:
      - 8046:8046
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHANNEL=${TELEGRAM_CHANNEL}
      - CMC_API_KEY=${CMC_API_KEY}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - fastapi_crawler_redis
      - fastapi_crawler_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8046/health"]
      interval: 30s
      timeout: 10s
      retries: 3
