services:
  fastapi-crawler:
    build: .
    ports:
      - 8046:8046
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHANNEL=${TELEGRAM_CHANNEL}
      - CMC_API_KEY=${CMC_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8046/health"]
      interval: 30s
      timeout: 10s
      retries: 3
